### ISSUE TITLE
when iam trying to make my led display circuit like shematic this error appear TypeError: in method 'FOOTPRINT_SetPosition', argument 2 of type 'wxPoint const &'

### ISSUE THREAD

**Issue by fouad1233** [ian-ross/kicad-plugins#14]
```
Traceback (most recent call last):

File "/Users/fuad/Documents/KiCad/6.0/scripting/plugins/kicad-plugins-main/SchematicPositionsToLayout.py", line 177, in Run
self.DoRun()

File "/Users/fuad/Documents/KiCad/6.0/scripting/plugins/kicad-plugins-main/SchematicPositionsToLayout.py", line 239, in DoRun
move_modules(components, board, offsets)

File "/Users/fuad/Documents/KiCad/6.0/scripting/plugins/kicad-plugins-main/SchematicPositionsToLayout.py", line 160, in move_modules
module.SetPosition(new_pos)

File "/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pcbnew.py", line 17267, in SetPosition
return _pcbnew.FOOTPRINT_SetPosition(self, aPos)

TypeError: in method 'FOOTPRINT_SetPosition', argument 2 of type 'wxPoint const &'

```
my shematic is as follow:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/85384184/225752278-634c4065-485d-4ade-830f-f4b16b3ea174.png">

**Comment by ian-ross** [comment]
I think you might be using the wrong version of the script there. There are two versions: `SchematicPositionsToLayout.py` is for KiCad **v7**, and `SchematicPositionsToLayout_V5_V6.py` is for KiCad **v5** and **v6**. The line numbers in the stack trace make it look as though you're using the v7 script, but you're using it with KiCad v6. The `pcbnew` API changed between v6 and v7, so you need to use the right script for the KiCad version you're using.
